"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os  # 👈 Adicionado para configuração de templates

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure--7e-jvnz!*zb$3cmx=m(xnxv3-$859+hjbd766*$^#%7k^%dq5'

DEBUG = True

ALLOWED_HOSTS = []


# =============================================================================
# 🎯 MODIFICAÇÕES PARA O PROJETO CORPSCHEDULE
# =============================================================================

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 👇 Apps do nosso projeto (ADICIONE ESTAS LINHAS)
    'core',
    'accounts',
    'scheduling',
]

# 👇 Configuração do Usuário Personalizado (ESSENCIAL)
AUTH_USER_MODEL = 'accounts.User'

# 👇 Evita warning de primary keys no Django 4+
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# 👇 Configuração de Templates com DIRS apontando para pasta 'templates' na raiz
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 👈 ALTERADO: Adicionado caminho para templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'pt-br'  # 👈 ALTERADO: Português do Brasil

TIME_ZONE = 'America/Sao_Paulo'  # 👈 ALTERADO: Fuso horário do Brasil

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# 👈 Adicionado: Diretório para arquivos estáticos na raiz
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]